"""Export endpoints.

Implemented now: CSV (original data), JSON (profile), Python notebook (.ipynb),
SQL (CREATE TABLE from inferred schema), Excel (data + profile workbook). PDF and
PowerPoint are produced client-side from the generated report/HTML preview, so the
server returns 501 for them with a clear message.
"""
from __future__ import annotations

import io
import json

import pandas as pd
from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.responses import Response
from sqlalchemy import select
from sqlalchemy.orm import Session

from app.api.resources import get_owned_dataset
from app.core.database import get_db
from app.models import Dataset, ProfileReport
from app.services.dataset_io import read_dataset_dataframe
from app.services.storage import get_storage

router = APIRouter(tags=["exports"])

_READY = {"csv", "json", "notebook", "sql", "excel"}
_PLANNED = {"pdf", "powerpoint"}
_EXCEL_ROW_CAP = 100_000


@router.get("/datasets/{dataset_id}/exports")
def list_export_formats(dataset: Dataset = Depends(get_owned_dataset)) -> dict:
    return {
        "dataset_id": dataset.id,
        "formats": [
            {"id": f, "status": "ready"} for f in sorted(_READY)
        ]
        + [{"id": f, "status": "planned"} for f in sorted(_PLANNED)],
    }


def _sql_schema(dataset: Dataset, profile: dict) -> str:
    type_map = {
        "numeric": "DOUBLE PRECISION",
        "boolean": "BOOLEAN",
        "datetime": "TIMESTAMP",
        "categorical": "VARCHAR(255)",
        "text": "TEXT",
    }
    cols = profile.get("columns", [])
    table = "".join(c for c in dataset.name.lower().replace(" ", "_") if c.isalnum() or c == "_")
    lines = [f"CREATE TABLE {table or 'dataset'} ("]
    defs = [f"    \"{c['name']}\" {type_map.get(c['semantic_type'], 'TEXT')}" for c in cols]
    lines.append(",\n".join(defs))
    lines.append(");")
    return "\n".join(lines)


def _notebook(dataset: Dataset, profile: dict) -> str:
    cells = [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [f"# {dataset.name} - starter analysis\n",
                       "Generated by DataMind AI."],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import pandas as pd\n",
                f"df = pd.read_csv('{dataset.original_filename or 'data.csv'}')\n",
                "df.head()",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": ["df.describe(include='all')"],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": ["df.isna().mean().sort_values(ascending=False)"],
        },
    ]
    nb = {
        "cells": cells,
        "metadata": {"language_info": {"name": "python"}},
        "nbformat": 4,
        "nbformat_minor": 5,
    }
    return json.dumps(nb, indent=1)


def _excel(dataset: Dataset, profile: dict) -> bytes:
    """Workbook with the raw data plus a profile summary sheet."""
    df = read_dataset_dataframe(dataset)
    if len(df) > _EXCEL_ROW_CAP:
        df = df.head(_EXCEL_ROW_CAP)

    summary = profile.get("dataset_summary", {})
    quality = profile.get("quality", {})
    overview = pd.DataFrame(
        [
            ("Dataset", dataset.name),
            ("Rows", summary.get("rows", len(df))),
            ("Columns", summary.get("columns", df.shape[1])),
            ("Duplicate rows", summary.get("duplicate_rows", 0)),
            ("Missing cells", summary.get("total_missing_cells", 0)),
            ("Quality grade", quality.get("grade", "n/a")),
            ("Quality score", quality.get("score", 0)),
        ],
        columns=["Metric", "Value"],
    )
    dtypes = profile.get("dtypes", {})
    columns_df = pd.DataFrame(
        [(k, v) for k, v in dtypes.items()], columns=["Column", "Type"]
    )

    buffer = io.BytesIO()
    with pd.ExcelWriter(buffer, engine="openpyxl") as writer:
        overview.to_excel(writer, sheet_name="Summary", index=False)
        if not columns_df.empty:
            columns_df.to_excel(writer, sheet_name="Columns", index=False)
        df.to_excel(writer, sheet_name="Data", index=False)
    return buffer.getvalue()


@router.get("/datasets/{dataset_id}/export")
def export_dataset(
    format: str,
    dataset: Dataset = Depends(get_owned_dataset),
    db: Session = Depends(get_db),
) -> Response:
    fmt = format.lower()
    if fmt in _PLANNED:
        raise HTTPException(
            status_code=status.HTTP_501_NOT_IMPLEMENTED,
            detail=f"'{fmt}' export is planned. Use the generated report as source content.",
        )
    if fmt not in _READY:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Unknown export format")

    if fmt == "csv":
        try:
            raw = get_storage().get(dataset.storage_key)
        except FileNotFoundError:
            raise HTTPException(status_code=404, detail="Dataset file not found")
        return Response(
            content=raw,
            media_type="text/csv",
            headers={"Content-Disposition": f'attachment; filename="{dataset.name}.csv"'},
        )

    profile_row = db.scalar(select(ProfileReport).where(ProfileReport.dataset_id == dataset.id))
    profile = profile_row.report if profile_row else {}

    if fmt == "json":
        return Response(
            content=json.dumps(profile, indent=2),
            media_type="application/json",
            headers={"Content-Disposition": f'attachment; filename="{dataset.name}-profile.json"'},
        )
    if fmt == "sql":
        return Response(
            content=_sql_schema(dataset, profile),
            media_type="application/sql",
            headers={"Content-Disposition": f'attachment; filename="{dataset.name}.sql"'},
        )
    if fmt == "excel":
        try:
            content = _excel(dataset, profile)
        except FileNotFoundError:
            raise HTTPException(status_code=404, detail="Dataset file not found")
        return Response(
            content=content,
            media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            headers={"Content-Disposition": f'attachment; filename="{dataset.name}.xlsx"'},
        )
    # notebook
    return Response(
        content=_notebook(dataset, profile),
        media_type="application/x-ipynb+json",
        headers={"Content-Disposition": f'attachment; filename="{dataset.name}.ipynb"'},
    )
