"""Native renderers: report document -> Markdown / standalone HTML.

The HTML renderer produces a self-contained, print-ready document with
consulting-grade typography: branded cover, table of contents, numbered
sections, styled tables and footer page numbers (via CSS paged media).
"""
from __future__ import annotations

import html as _html
from datetime import datetime
from typing import Any


def render_markdown(doc: dict[str, Any]) -> str:
    lines: list[str] = [
        f"# {doc['title']} — {doc['subtitle']}",
        "",
        f"*Generated by {doc['brand']} on {_date(doc)}*",
        "",
        "## Table of Contents",
    ]
    for i, sec in enumerate(doc["sections"], start=1):
        lines.append(f"{i}. {sec['heading']}")
    lines.append("")

    for i, sec in enumerate(doc["sections"], start=1):
        lines += [f"## {i}. {sec['heading']}", ""]
        for block in sec["blocks"]:
            lines += _md_block(block)
        lines.append("")
    return "\n".join(lines)


def _md_block(block: dict[str, Any]) -> list[str]:
    kind = block.get("type")
    if kind == "p":
        return [block.get("text", ""), ""]
    if kind == "callout":
        return [f"> {block.get('text', '')}", ""]
    if kind == "kv":
        out = ["| | |", "| --- | --- |"]
        out += [f"| **{k}** | {v} |" for k, v in block.get("items", [])]
        out.append("")
        return out
    if kind == "list":
        marker = "1." if block.get("ordered") else "-"
        return [f"{marker} {item}" for item in block.get("items", [])] + [""]
    if kind == "table":
        cols = block.get("columns", [])
        out = ["| " + " | ".join(cols) + " |", "| " + " | ".join(["---"] * len(cols)) + " |"]
        out += ["| " + " | ".join(str(c) for c in row) + " |" for row in block.get("rows", [])]
        out.append("")
        return out
    return []


# --- HTML --------------------------------------------------------------------
_CSS = """
:root { --ink:#16233b; --muted:#5b6b84; --accent:#2563eb; --line:#e3e8f0; --bg:#f7f9fc; }
* { box-sizing: border-box; }
body { margin:0; color:var(--ink); background:#fff;
  font:14px/1.65 'Segoe UI', 'Helvetica Neue', Arial, sans-serif; }
.page { max-width: 860px; margin: 0 auto; padding: 48px 56px; }
.cover { border-bottom: 4px solid var(--accent); padding-bottom: 32px; margin-bottom: 40px; }
.brand { color: var(--accent); font-weight: 700; letter-spacing: .12em;
  text-transform: uppercase; font-size: 12px; }
h1 { font-size: 34px; margin: 12px 0 4px; letter-spacing: -0.02em; }
.subtitle { color: var(--muted); font-size: 17px; margin: 0; }
.meta { color: var(--muted); font-size: 12px; margin-top: 16px; }
.toc { background: var(--bg); border: 1px solid var(--line); border-radius: 10px;
  padding: 20px 28px; margin-bottom: 40px; }
.toc h2 { margin: 0 0 10px; font-size: 15px; text-transform: uppercase;
  letter-spacing: .08em; color: var(--muted); }
.toc ol { margin: 0; padding-left: 20px; }
.toc a { color: var(--ink); text-decoration: none; }
.toc a:hover { color: var(--accent); }
section { margin-bottom: 36px; page-break-inside: avoid; }
h2.sec { font-size: 20px; border-bottom: 2px solid var(--line); padding-bottom: 8px;
  margin: 0 0 16px; }
h2.sec .num { color: var(--accent); margin-right: 10px; font-variant-numeric: tabular-nums; }
p { margin: 0 0 12px; }
table { border-collapse: collapse; width: 100%; margin: 0 0 16px; font-size: 13px; }
th { background: var(--bg); text-align: left; font-weight: 600; }
th, td { border: 1px solid var(--line); padding: 7px 11px; }
tr:nth-child(even) td { background: #fbfcfe; }
.kv td:first-child { font-weight: 600; width: 34%; background: var(--bg); }
.callout { border-left: 4px solid var(--accent); background: var(--bg);
  padding: 14px 18px; border-radius: 0 8px 8px 0; margin: 0 0 16px; font-style: italic; }
ul, ol { margin: 0 0 14px; padding-left: 22px; }
li { margin-bottom: 6px; }
footer { border-top: 1px solid var(--line); margin-top: 48px; padding-top: 14px;
  display: flex; justify-content: space-between; color: var(--muted); font-size: 11px; }
@page { margin: 20mm 16mm; @bottom-right { content: counter(page); } }
@media print { .page { padding: 0; max-width: none; } }
"""


def render_html(doc: dict[str, Any]) -> str:
    esc = _html.escape
    parts: list[str] = [
        "<!doctype html><html><head><meta charset='utf-8'/>",
        f"<title>{esc(doc['title'])} — {esc(doc['subtitle'])}</title>",
        f"<style>{_CSS}</style></head><body><div class='page'>",
        "<div class='cover'>",
        f"<div class='brand'>{esc(doc['brand'])}</div>",
        f"<h1>{esc(doc['title'])}</h1>",
        f"<p class='subtitle'>{esc(doc['subtitle'])}</p>",
        f"<div class='meta'>Generated {esc(_date(doc))} · Confidential — internal use</div>",
        "</div>",
        "<div class='toc'><h2>Table of Contents</h2><ol>",
    ]
    for i, sec in enumerate(doc["sections"], start=1):
        parts.append(f"<li><a href='#sec-{i}'>{esc(sec['heading'])}</a></li>")
    parts.append("</ol></div>")

    for i, sec in enumerate(doc["sections"], start=1):
        parts.append(f"<section id='sec-{i}'><h2 class='sec'><span class='num'>{i:02d}</span>{esc(sec['heading'])}</h2>")
        for block in sec["blocks"]:
            parts.append(_html_block(block))
        parts.append("</section>")

    parts.append(
        f"<footer><span>{esc(doc['brand'])} · {esc(doc['title'])}</span>"
        f"<span>{esc(doc['subtitle'])}</span></footer>"
    )
    parts.append("</div></body></html>")
    return "".join(parts)


def _html_block(block: dict[str, Any]) -> str:
    esc = _html.escape
    kind = block.get("type")
    if kind == "p":
        return f"<p>{esc(block.get('text', ''))}</p>"
    if kind == "callout":
        return f"<div class='callout'>{esc(block.get('text', ''))}</div>"
    if kind == "kv":
        rows = "".join(
            f"<tr><td>{esc(str(k))}</td><td>{esc(str(v))}</td></tr>"
            for k, v in block.get("items", [])
        )
        return f"<table class='kv'>{rows}</table>"
    if kind == "list":
        tag = "ol" if block.get("ordered") else "ul"
        items = "".join(f"<li>{esc(str(i))}</li>" for i in block.get("items", []))
        return f"<{tag}>{items}</{tag}>"
    if kind == "table":
        head = "".join(f"<th>{esc(str(c))}</th>" for c in block.get("columns", []))
        body = "".join(
            "<tr>" + "".join(f"<td>{esc(str(c))}</td>" for c in row) + "</tr>"
            for row in block.get("rows", [])
        )
        return f"<table><thead><tr>{head}</tr></thead><tbody>{body}</tbody></table>"
    return ""


def _date(doc: dict[str, Any]) -> str:
    raw = doc.get("generated_at", "")
    try:
        return datetime.fromisoformat(raw).strftime("%B %d, %Y")
    except ValueError:
        return raw
